apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.cicd.yml -o k8s-cicd/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: jenkins
